// LemonSqueezy Payment Integration for SocialPulse AI
// Auto-generated by setup-all-payments.sh

export interface LemonSqueezyCheckout {
  checkoutUrl: string;
  orderId?: string;
}

export interface LemonSqueezySubscription {
  id: string;
  status: 'active' | 'on_trial' | 'past_due' | 'canceled' | 'unpaid';
  planId: string;
  currentPeriodStart: string;
  currentPeriodEnd: string;
  cancelAtPeriodEnd: boolean;
}

export const PLANS = {
  FREE: {
    id: 'free',
    name: 'Free',
    price: 0,
    features: [
      'Limited accounts (2/month)',
      'Basic features',
      'Email support',
    ],
    limits: {
      accounts: 2,
    }
  },
  STARTER: {
    id: 'starter',
    variantId: process.env.NEXT_PUBLIC_LEMONSQUEEZY_STARTER_VARIANT_ID || '',
    name: 'Starter',
    price: 12,
    features: [
      'Extended accounts limits',
      'Priority processing',
      'Email support',
    ],
    limits: {
      accounts: -1,
    }
  },
  PRO: {
    id: 'pro',
    variantId: process.env.NEXT_PUBLIC_LEMONSQUEEZY_PRO_VARIANT_ID || '',
    name: 'Pro',
    price: 29,
    features: [
      'Unlimited accounts',
      'Advanced AI features',
      'API access',
      'Priority support',
    ],
    limits: {
      accounts: -1,
    }
  }
} as const;

export type PlanType = keyof typeof PLANS;

export async function createCheckout(
  planId: 'starter' | 'pro',
  userId: string,
  email: string
): Promise<LemonSqueezyCheckout> {
  const plan = planId === 'starter' ? PLANS.STARTER : PLANS.PRO;
  const response = await fetch('/api/checkout/create', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ variantId: plan.variantId, userId, email }),
  });
  if (!response.ok) throw new Error('Failed to create checkout');
  return response.json();
}

export async function getCurrentSubscription(userId: string): Promise<LemonSqueezySubscription | null> {
  const response = await fetch(`/api/subscriptions/current?userId=${userId}`);
  if (!response.ok) {
    if (response.status === 404) return null;
    throw new Error('Failed to fetch subscription');
  }
  return response.json();
}

export async function cancelSubscription(subscriptionId: string): Promise<{ canceledAt: string }> {
  const response = await fetch('/api/subscriptions/cancel', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ subscriptionId }),
  });
  if (!response.ok) throw new Error('Failed to cancel subscription');
  return response.json();
}

export async function checkUsageLimit(
  userId: string,
  featureKey: string
): Promise<{ allowed: boolean; used: number; limit: number }> {
  const response = await fetch(`/api/usage/check?userId=${userId}&feature=${featureKey}`);
  if (!response.ok) throw new Error('Failed to check usage');
  return response.json();
}

export async function incrementUsage(
  userId: string,
  featureKey: string
): Promise<{ newCount: number }> {
  const response = await fetch('/api/usage/increment', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ userId, featureKey }),
  });
  if (!response.ok) throw new Error('Failed to increment usage');
  return response.json();
}
